import type { GameDate } from "./time";
import type { EntityId } from "./kingdom";

export type QuestStatus = "available" | "active" | "completed" | "failed" | "expired";

export type ObjectiveType =
  | "defeat_target"
  | "deliver_item"
  | "escort_npc"
  | "collect_item"
  | "talk_to_npc"
  | "clear_location";

export interface QuestObjective {
  id: EntityId;
  type: ObjectiveType;
  /** Human-readable imperative text ("Clear the bandits from the roads"),
   * shown in JourneyCard's checklist. Added in the UI polish pass — before
   * this, objectives had no displayable text at all, only a type enum. */
  label: string;
  targetId: EntityId | null;
  quantity: number;
  progress: number;
  complete: boolean;
}

export interface QuestReward {
  gold: number;
  reputationDelta: number;
  factionId: EntityId | null;
  itemIds: EntityId[];
}

/**
 * Quests are never hand-authored content; they are generated by the
 * QuestGenerator from a QuestTemplate matched against current world state,
 * so `originEventId` and `contextSummary` always trace back to *why*
 * this quest exists (a famine, a closed trade route, a bandit raid...).
 */
export interface Quest {
  id: EntityId;
  templateId: string;
  title: string;
  /** Filled-in flavor text explaining the quest's cause, e.g. "Wolves attacked the Millbrook farms after the famine..." */
  contextSummary: string;
  giverNpcId: EntityId;
  originEventId: EntityId | null;
  status: QuestStatus;
  objectives: QuestObjective[];
  reward: QuestReward;
  issuedOn: GameDate;
  expiresOn: GameDate | null;
}

/** Rule-based recipe the QuestGenerator matches against world state to produce a Quest. */
export interface QuestTemplate {
  id: string;
  title: string;
  /** Human-readable description of when this template applies, for maintainers. */
  triggerDescription: string;
  category: "combat" | "delivery" | "social" | "exploration";
}
